### 1. Create a NumPy array and perform basic operations

In [1]:
import numpy as np

# Create a NumPy array
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Basic operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print(addition, subtraction, multiplication, sep="\n")

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


### 2. Calculate statistical measures like mean, median, and standard deviation

In [2]:
# Mean
mean_value = np.mean(array1)

# Median
median_value = np.median(array1)

# Standard Deviation
std_dev = np.std(array1)

print(mean_value, median_value, std_dev, sep="\n")

3.0
3.0
1.4142135623730951


### 3. Reshape and slice NumPy arrays to extract specific data elements

In [3]:
# Reshape the array
reshaped_array = array1.reshape(1, 5)

# Slice the array (e.g., first three elements)
sliced_array = array1[:3]

print(reshaped_array, sliced_array, sep="\n")

[[1 2 3 4 5]]
[1 2 3]


### 4. Perform element-wise operations and broadcasting with NumPy arrays

In [4]:
# Element-wise operation: square the elements
squared_array = array1 ** 2

# Broadcasting: add a scalar to each element
broadcasted_array = array1 + 10

print(squared_array, broadcasted_array, sep="\n")

[ 1  4  9 16 25]
[11 12 13 14 15]


### 5. Apply mathematical functions (e.g., exponential, logarithm) to NumPy arrays

In [5]:
# Exponential function
exp_array = np.exp(array1)

# Logarithm function
log_array = np.log(array1)

print(exp_array, log_array, sep="\n")

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
